# Generated by Django 4.0.1 on 2023-01-18 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="É necessario que o numero esteja com esta formatação:                     '+55 55 55555-5555'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
